apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gbnn9xxjs-python 
  janus-idp.io/tekton: gbnn9xxjs-python
  backstage.io/kubernetes-id: gbnn9xxjs-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gbnn9xxjs-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  