apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gbnn9xxjs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gbnn9xxjs-python 
  name: gbnn9xxjs-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gbnn9xxjs-python 
